version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.9"

  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
      - python -m pip install --upgrade --no-cache-dir mkdocs-material
      - python -m pip install --upgrade --no-cache-dir mkdocs-macros-plugin
      - python -m pip install --upgrade --no-cache-dir mkdocstrings-python

    post_install:
      - poetry install --only docs